title: "Percelic Blog"
remote_theme: just-the-docs/just-the-docs

back_to_top: true  
back_to_top_text: "Back to top"  

last_edit_timestamp: true  
last_edit_time_format: "%Y-%m-%d %H:%M"

logo: "/assets/images/KakaoTalk_20210702_162454877_04.jpg"